2022-01-22 20:20:27,422 INFO     server.py Запущен сервер, порт для подключений: 7777, адрес с которого принимаются подключения: .
2022-01-22 20:20:42,585 INFO     server.py Установлено соедение с ПК ('127.0.0.1', 55042)
2022-01-22 20:20:42,585 DEBUG    server.py Получено сообщение {'action': 'presence', 'time': 1642864842.5549119, 'user': {'account_name': 'guest'}}
2022-01-22 20:20:42,585 DEBUG    server.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1642864842.5549119, 'user': {'account_name': 'guest'}}
2022-01-22 20:20:42,585 INFO     server.py Сформирован ответ клиенту {'response': 400, 'error': 'Bad Request'}
2022-01-22 20:20:42,585 DEBUG    server.py Соединение с клиентом ('127.0.0.1', 55042) закрывается.
2022-01-22 20:21:21,009 INFO     server.py Установлено соедение с ПК ('127.0.0.1', 55077)
2022-01-22 20:21:21,009 DEBUG    server.py Получено сообщение {'action': 'presence', 'time': 1642864881.0099347, 'user': {'account_name': 'guest'}}
2022-01-22 20:21:21,009 DEBUG    server.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1642864881.0099347, 'user': {'account_name': 'guest'}}
2022-01-22 20:21:21,009 INFO     server.py Сформирован ответ клиенту {'response': 400, 'error': 'Bad Request'}
2022-01-22 20:21:21,009 DEBUG    server.py Соединение с клиентом ('127.0.0.1', 55077) закрывается.
2022-01-22 20:24:13,220 INFO     server.py Установлено соедение с ПК ('127.0.0.1', 55209)
2022-01-22 20:24:13,220 DEBUG    server.py Получено сообщение {'action': 'presence', 'time': 1642865053.2207546, 'user': {'account_name': 'Guest'}}
2022-01-22 20:24:13,220 DEBUG    server.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1642865053.2207546, 'user': {'account_name': 'Guest'}}
2022-01-22 20:24:13,220 INFO     server.py Сформирован ответ клиенту {'response': 200}
2022-01-22 20:24:13,220 DEBUG    server.py Соединение с клиентом ('127.0.0.1', 55209) закрывается.
